version: '3'
services:
  backend:
    build: ./Backend
    image: containerxisheng.azurecr.io/backend:v3
    container_name: backend
    environment:
      SERVER_PORT: 80
    ports:
      - "80:80"

  frontend:
    build: ./Frontend
    image: containerxisheng.azurecr.io/frontend:v3
    container_name: frontend
    environment:
      SERVER_PORT: 80
      BACKEND_HOST: http://backend
    ports:
      - "8000:80"
